using KGERP.Data.CustomModel;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace KGERP.Service.Interface
{
    public interface IVendorService
    {
        Task<VendorModel> GetVendors(int companyId, int vendorTypeId);
        List<SelectModel> GetVendorSelectModels(int vendorTypeId);
        List<SelectModel> GetCustomerSelectModel(int companyId, int vendorType);
        VendorModel GetVendor(int customerId);
        List<CustomerReceivableCustomModel> GetCustomerReceivables(int vendorId);
        List<CustomerLedgerCustomModel> GetCustomerLedger(int id);
        object GetCustomerAutoComplete(string prefix, int companyId);
        object CustomerAssociatesCustomerId( int customerId);
        object GetClientAutoComplete(string prefix, int companyId);
        object GetSupplierAutoComplete(string prefix, int companyId);
        VendorModel GetVendorByType(int id, int vendorTypeId);
        Task<VendorModel> GetCustomerPayments(int companyId);
        List<VendorModel> GetCustomerPayments(string searchText, int companyId, int customer);

        Task<bool> SaveVendor(int v, VendorModel vendor, string message);
        string GetAutoGeneratedVendorCode(int companyId, int upazilaId, int vendorId);
        VendorModel GetSupplier(int supplierId);
        VendorModel GetVendorPaymentStatus(int customerId);
        List<MonthSelectModel> GetMonthSelectModes();
        List<VendorModel> GetAllCustomers(int vendorTypeId);
        bool BulkCustomerSave(List<VendorModel> vendors);
        List<SelectModel> GetCustomerSelectModelsByCompany(int companyId, int customer);
        List<SelectModel> GetCustomerNameSelectModel(int? companyId, int customer);
        bool DeleteVendor(int id);
        List<SelectModel> GetCustomerSelectModels(int companyId, string productType);
        object GetRentCompanyAutoComplete(string prefix, int companyId);

        Task<VendorDeedListVm> GetAllVendorDeed(int companyId);
        Task<int> SaveVendorDeed(VendorDeedVm model);
       
        Task<VendorDeedVm> GetVendorDeedById(int vendorDeedId);
        Task<bool> RemoveVendorDeed(int vendorDeedId);

    }
}
