//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_ChequeInfo
    {
        public Nullable<int> CompanyId { get; set; }
        public int ActChequeInfoId { get; set; }
        public int BankBranchId { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public string PayTo { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> SignatoryId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BankBranch BankBranch { get; set; }
        public virtual Accounting_Signatory Accounting_Signatory { get; set; }
    }
}
