//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetFileAttach
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Extention { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
