//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendancePolicy
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string LatePresentRange { get; set; }
        public string AbsentRange { get; set; }
        public string OvertimeRange { get; set; }
        public string TimeLatePresent { get; set; }
        public string TimeAbsent { get; set; }
        public string EarlyOut { get; set; }
        public string LateOut { get; set; }
        public System.DateTime EndDate { get; set; }
        public string HalfDay { get; set; }
        public string HalfHour { get; set; }
        public int CountDelay { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
