//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillRequisitionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillRequisitionMaster()
        {
            this.BillRequisitionVoucherMaps = new HashSet<BillRequisitionVoucherMap>();
            this.BillRequisitionApprovals = new HashSet<BillRequisitionApproval>();
            this.BillRequisitionDetails = new HashSet<BillRequisitionDetail>();
            this.BillReqApprovalHistories = new HashSet<BillReqApprovalHistory>();
        }
    
        public long BillRequisitionMasterId { get; set; }
        public System.DateTime BRDate { get; set; }
        public string BillRequisitionNo { get; set; }
        public int ProjectTypeId { get; set; }
        public int BOQItemId { get; set; }
        public int CostCenterId { get; set; }
        public int BillRequisitionTypeId { get; set; }
        public string Description { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Accounting_CostCenter Accounting_CostCenter { get; set; }
        public virtual Accounting_CostCenterType Accounting_CostCenterType { get; set; }
        public virtual Company Company { get; set; }
        public virtual BillRequisitionType BillRequisitionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRequisitionVoucherMap> BillRequisitionVoucherMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRequisitionApproval> BillRequisitionApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRequisitionDetail> BillRequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReqApprovalHistory> BillReqApprovalHistories { get; set; }
    }
}
