//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoqBNEApprovalHistroy
    {
        public long BoqBNEApprovalHistroyId { get; set; }
        public long BoqBudgetId { get; set; }
        public decimal PreEstimatedQty { get; set; }
        public decimal PreUnitPrice { get; set; }
        public int ApprovalStatusId { get; set; }
        public string ApprovalRemarks { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BoQItemProductMap BoQItemProductMap { get; set; }
    }
}
