//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChequeBook()
        {
            this.ChequeRegisters = new HashSet<ChequeRegister>();
        }
    
        public long ChequeBookId { get; set; }
        public int BankAccountInfoId { get; set; }
        public string ChequeBookNo { get; set; }
        public int BookFirstPageNumber { get; set; }
        public int BookLastPageNumber { get; set; }
        public int TotalBookPage { get; set; }
        public int UsedBookPage { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BankAccountInfo BankAccountInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeRegister> ChequeRegisters { get; set; }
    }
}
