//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients_BasicInfo
    {
        public long Basic_Info_id { get; set; }
        public string Name { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public Nullable<int> ProjectName { get; set; }
        public string ClientAutoId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
