//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsInfo_Del
    {
        public long cli_id_Del { get; set; }
        public string ClientAutoId { get; set; }
        public string NameOfApplicant { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string SpousesName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateOfBirrh { get; set; }
        public string TelOffice { get; set; }
        public string TelephoneNoRes { get; set; }
        public string Fax { get; set; }
        public string Profession { get; set; }
        public string OfficialAddress { get; set; }
        public string ProjectName { get; set; }
        public string NationalIdNo { get; set; }
        public string TinNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailAdderss { get; set; }
        public string PassportNo { get; set; }
        public string Designation { get; set; }
        public string BankDraftPayOrdChq { get; set; }
        public string RepresentativeName { get; set; }
        public string Nominee { get; set; }
        public string Nominee_FullName { get; set; }
        public string Nominee_FathersName { get; set; }
        public string Nominee_MothersName { get; set; }
        public string Nominee_perAdderss { get; set; }
        public string ReletionwithApplicant { get; set; }
        public string Nationlaty { get; set; }
        public string Natioal_IdNo { get; set; }
        public string TleOrMobileNo { get; set; }
        public string Email { get; set; }
        public string ClientImageLink { get; set; }
        public string NomineeImageLink { get; set; }
        public byte[] ClientPicture { get; set; }
        public byte[] NomineePicture { get; set; }
    }
}
