//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainManagement
    {
        public int ComplainId { get; set; }
        public Nullable<int> ComplainTypeId { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ComplainDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActionDescription { get; set; }
        public string ActionTakerBy { get; set; }
        public Nullable<System.DateTime> ActionTakerDate { get; set; }
        public string ActionTakenBy { get; set; }
        public Nullable<System.DateTime> ActionTakenDate { get; set; }
        public Nullable<System.DateTime> ActionModifiedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int IsActionTaked { get; set; }
        public bool IsComplainClosed { get; set; }
        public string DeleverdBy { get; set; }
        public string ActionAssignTo { get; set; }
        public string SolvingDescription { get; set; }
        public string Remarks { get; set; }
        public bool IsComplainSolved { get; set; }
    
        public virtual ComplainType ComplainType { get; set; }
    }
}
