//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyVoucher
    {
        public long CompanyVoucherId { get; set; }
        public int CompanyId { get; set; }
        public int VoucherId { get; set; }
        public string TransactionType { get; set; }
        public string ReferenceNo { get; set; }
    }
}
