//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvertedProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConvertedProduct()
        {
            this.ConvertedProductDetails = new HashSet<ConvertedProductDetail>();
        }
    
        public int ConvertedProductId { get; set; }
        public string InvoiceNo { get; set; }
        public int CompanyId { get; set; }
        public int ConvertFrom { get; set; }
        public int ConvertTo { get; set; }
        public decimal ConvertedQty { get; set; }
        public Nullable<System.DateTime> ConvertedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ConvertStatus { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public decimal ConvertFromUnitPrice { get; set; }
        public decimal ConvertedUnitPrice { get; set; }
        public int RowNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConvertedProductDetail> ConvertedProductDetails { get; set; }
    }
}
