//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRecoverDetail
    {
        public long CreditRecoverDetailId { get; set; }
        public Nullable<long> CreditRecoverId { get; set; }
        public decimal RecoverAmount { get; set; }
        public Nullable<System.DateTime> RecoverDate { get; set; }
        public string Note { get; set; }
    
        public virtual CreditRecover CreditRecover { get; set; }
    }
}
