//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmSchedule
    {
        public int ScheduleId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public System.TimeSpan ScheduleTime { get; set; }
        public string ScheduleType { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsCompleted { get; set; }
    }
}
