//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNomineeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerNomineeInfo()
        {
            this.NomineePercentageMappings = new HashSet<NomineePercentageMapping>();
        }
    
        public long NomineeId { get; set; }
        public string NomineeName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public int CustomerId { get; set; }
        public int RelationId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ImageDocId { get; set; }
        public Nullable<long> NIDDocId { get; set; }
    
        public virtual PRM_Relation PRM_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NomineePercentageMapping> NomineePercentageMappings { get; set; }
        public virtual KGRECustomer KGRECustomer { get; set; }
    }
}
