//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.DemandItems = new HashSet<DemandItem>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public long DemandId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string DemandNo { get; set; }
        public Nullable<System.DateTime> DemandDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsInvoiceCreated { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StockInfoId { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public decimal Discount { get; set; }
        public decimal DicountAmount { get; set; }
        public bool IsSubmitted { get; set; }
        public int RequisitionType { get; set; }
        public decimal Amount { get; set; }
        public decimal SalesStatus { get; set; }
        public decimal CreditStatus { get; set; }
        public int HeadGLId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandItem> DemandItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
