//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandItemDetail
    {
        public System.Guid DemandItemDetailId { get; set; }
        public long DemandItemId { get; set; }
        public Nullable<long> DemandId { get; set; }
        public Nullable<int> RProductId { get; set; }
        public decimal RQty { get; set; }
        public decimal RExtraQty { get; set; }
        public decimal RStockQty { get; set; }
        public decimal RRequiredQty { get; set; }
        public decimal RUnitPrice { get; set; }
        public decimal RTotalAmount { get; set; }
    }
}
