//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandItem
    {
        public long DemandItemId { get; set; }
        public Nullable<long> DemandId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public long Qty { get; set; }
        public double UnitPrice { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal DiscountUnit { get; set; }
        public decimal DiscountAmount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public double ProductPrice { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
    
        public virtual Demand Demand { get; set; }
    }
}
