//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Audit
    {
        public long ChangId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public Nullable<long> HrAdminId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CardId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public string NationalId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritalTypeId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public string MobileNo { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string OfficeEmail { get; set; }
        public string FaxNo { get; set; }
        public string PABX { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string PassportNo { get; set; }
        public string TinNo { get; set; }
        public string SocialId { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> EmployeeCategoryId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public Nullable<int> OfficeTypeId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> DisverseMethodId { get; set; }
        public Nullable<int> DesignationFlag { get; set; }
        public string ImageFileName { get; set; }
        public string SignatureFileName { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndReason { get; set; }
        public string Remarks { get; set; }
        public int EmployeeOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SalaryTag { get; set; }
        public string Operation { get; set; }
    }
}
