//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTerritory
    {
        public string EmployeeId { get; set; }
        public string TerritoryId { get; set; }
    
        public virtual EmployeeTerritory EmployeeTerritories1 { get; set; }
        public virtual EmployeeTerritory EmployeeTerritory1 { get; set; }
    }
}
