//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public long FarmerId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<long> OfficerId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string NationalId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Spouse { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Upzila { get; set; }
        public string Village { get; set; }
        public Nullable<int> Payment { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
