//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetailInfo
    {
        public long IssueDetailId { get; set; }
        public Nullable<long> IssueMasterId { get; set; }
        public Nullable<int> RProductId { get; set; }
        public Nullable<decimal> RMQ { get; set; }
        public Nullable<long> RequisitionItemId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual IssueMasterInfo IssueMasterInfo { get; set; }
    }
}
