//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KGREProject
    {
        public int ProjectId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ProjectName { get; set; }
        public string Address { get; set; }
        public Nullable<int> TotalPlot { get; set; }
        public Nullable<int> TotalFlat { get; set; }
        public Nullable<int> UnitRate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsAccounting { get; set; }
    }
}
