//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KGREProjectDetail
    {
        public int ProjectDetailId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string FlatNo { get; set; }
        public string FlatFace { get; set; }
        public Nullable<int> NoofBed { get; set; }
        public Nullable<int> NoofWashroom { get; set; }
        public Nullable<int> NoofKitchen { get; set; }
        public Nullable<int> NoofBelcony { get; set; }
        public Nullable<bool> IsGarage { get; set; }
        public Nullable<bool> IsParking { get; set; }
        public Nullable<bool> IsBoundary { get; set; }
        public Nullable<int> RegularPriceSFT { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> RateSft { get; set; }
        public Nullable<int> UtilityCost { get; set; }
        public string Solar { get; set; }
        public string Others { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
