//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandNLegal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandNLegal()
        {
            this.FileAttachments = new HashSet<FileAttachment>();
        }
    
        public long OID { get; set; }
        public string CaseNo { get; set; }
        public string CourtName { get; set; }
        public string AdditionalDistrictCourt { get; set; }
        public Nullable<System.DateTime> FilingDate { get; set; }
        public string DefendantName { get; set; }
        public string DefendantFatherName { get; set; }
        public string DefendantMotherName { get; set; }
        public string BusinessOrganizationName { get; set; }
        public string MobileNo { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string ThanaUpazila { get; set; }
        public string VillageMohalla { get; set; }
        public string TradeLicenceNo { get; set; }
        public string NIDnPassportNo { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeIssueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BusinessAddress { get; set; }
        public string PlaintiffAppellant { get; set; }
        public string CaseType { get; set; }
        public string CaseStatus { get; set; }
        public Nullable<System.DateTime> WithdrawDismissCloseDate { get; set; }
        public Nullable<System.DateTime> PreviousDate1 { get; set; }
        public Nullable<System.DateTime> PreviousDate2 { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string CompanyName { get; set; }
        public string ResponsibleLayer { get; set; }
        public string CaseSummary { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
    }
}
