//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCInfo
    {
        public long LCId { get; set; }
        public int CompanyId { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public int LCType { get; set; }
        public string PINo { get; set; }
        public Nullable<decimal> LCValue { get; set; }
        public int SupplierId { get; set; }
        public Nullable<int> ProductOriginId { get; set; }
        public Nullable<int> OriginCountryId { get; set; }
        public Nullable<decimal> FreighterCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string InsuranceNo { get; set; }
        public Nullable<decimal> PremiumValue { get; set; }
        public bool IsSubmit { get; set; }
        public bool POCreated { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> HeadId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
