//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public long LeaveId { get; set; }
        public Nullable<long> Id { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public string EmployeeId { get; set; }
        public int LeaveCategoryId { get; set; }
        public System.DateTime SartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Days { get; set; }
        public string ApplicationTo { get; set; }
        public string ForwardTo { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string ForEmployeeId { get; set; }
        public int ForDesignationId { get; set; }
        public string ForNotes { get; set; }
        public string VerNotes { get; set; }
        public string ApproveNotes { get; set; }
        public string VerEmployeeId { get; set; }
        public int VerDesignationId { get; set; }
        public string ApprvEmployeeId { get; set; }
        public int ApprvDesignationId { get; set; }
        public int PostFlag { get; set; }
        public int PayHeadCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual LeaveCategory LeaveCategory { get; set; }
    }
}
