//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        public int loantype_id { get; set; }
        public string loantype_name { get; set; }
        public double maxloan_amt { get; set; }
        public int save_by { get; set; }
        public System.DateTime save_time { get; set; }
    }
}
