//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineePercentageMapping
    {
        public long NomineeMapId { get; set; }
        public long NomineeId { get; set; }
        public long ProductId { get; set; }
        public double Percentage { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CustomerNomineeInfo CustomerNomineeInfo { get; set; }
        public virtual CustomerGroupInfo CustomerGroupInfo { get; set; }
    }
}
