//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P
    {
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public int ProductId { get; set; }
        public string Company { get; set; }
        public string CompanyLogo { get; set; }
        public string StockName { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> OpeningRate { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public Nullable<decimal> OpeningValue { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> ReceivedRate { get; set; }
        public Nullable<decimal> ReceivedValue { get; set; }
        public Nullable<decimal> ConsumptionQty { get; set; }
        public Nullable<decimal> ConsumptionValue { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> ReturnValue { get; set; }
        public Nullable<decimal> SaleQty { get; set; }
        public Nullable<decimal> SaleValue { get; set; }
        public Nullable<decimal> ExcessQty { get; set; }
        public Nullable<decimal> ExcessValue { get; set; }
        public Nullable<decimal> LessQty { get; set; }
        public Nullable<decimal> LessValue { get; set; }
        public Nullable<decimal> ClosingQty { get; set; }
        public Nullable<decimal> ClosingRate { get; set; }
        public Nullable<decimal> StockAmount { get; set; }
    }
}
