//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLeave
    {
        public long Employee { get; set; }
        public int LeaveCategoryId { get; set; }
        public string LeaveCategory { get; set; }
        public int MaxDays { get; set; }
        public int LeaveAvailed { get; set; }
        public string LeaveYear { get; set; }
        public string Gender { get; set; }
        public string MaritalType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
