//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public long ProductDetailsId { get; set; }
        public long StoreDetailsId { get; set; }
        public int ProductId { get; set; }
        public string EngineNo { get; set; }
        public string ChassissNO { get; set; }
        public string FuelPumpSlNo { get; set; }
        public string BetteryNo { get; set; }
        public string RearTyreLH { get; set; }
        public string RearTyreRH { get; set; }
        public string RearTyreFLH { get; set; }
        public string RearTyreFRH { get; set; }
        public string Color { get; set; }
        public Nullable<int> IsDelevered { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LcNo { get; set; }
        public Nullable<long> DeliveredId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StoreDetail StoreDetail { get; set; }
    }
}
