//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderTemplate
    {
        public int PurchaseOrderTemplateId { get; set; }
        public long PurchaseOrderId { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
    }
}
