//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public long PurchaseOrderDetailId { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public decimal PurchaseQty { get; set; }
        public decimal DemandRate { get; set; }
        public decimal PurchaseRate { get; set; }
        public decimal QCRate { get; set; }
        public decimal PurchaseAmount { get; set; }
        public int PackSize { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FinishProductBOMId { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
