//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationSubmit
    {
        public long QuotationSubmitId { get; set; }
        public long QuotationMasterId { get; set; }
        public int SupplierId { get; set; }
        public int MaterialId { get; set; }
        public decimal UnitPrice { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual QuotationMaster QuotationMaster { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
