//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportApprovalDetail
    {
        public long ReportApprovalDetail1 { get; set; }
        public Nullable<long> ReportApprovalId { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int Accounting_SignatoryId { get; set; }
        public int SignatoryOrderNo { get; set; }
        public int ApprovalStatus { get; set; }
        public Nullable<int> ForwardedId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public long ApprovalFor { get; set; }
    }
}
