//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingPerson
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string rep_person_id { get; set; }
        public string def_rep_person_id { get; set; }
        public int active { get; set; }
        public System.DateTime date { get; set; }
    }
}
