//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItem
    {
        public int RequisitionItemId { get; set; }
        public int RequisitionId { get; set; }
        public Nullable<int> ProductFormulaId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public decimal Qty { get; set; }
        public decimal InputQty { get; set; }
        public decimal OutputQty { get; set; }
        public decimal OverHead { get; set; }
        public decimal ProcessLoss { get; set; }
        public decimal ActualProcessLoss { get; set; }
        public decimal RMCost { get; set; }
        public int BagQty { get; set; }
        public Nullable<int> BagId { get; set; }
        public decimal BagUnitPrice { get; set; }
        public decimal RMCostRate { get; set; }
        public decimal BagRate { get; set; }
        public decimal ProductionRate { get; set; }
        public string RequisitionItemStatus { get; set; }
        public string IssueBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public bool IsActive { get; set; }
        public decimal TPPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
