//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReturnDetail
    {
        public long SaleReturnDetailId { get; set; }
        public Nullable<long> SaleReturnId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> COGSRate { get; set; }
        public Nullable<decimal> BaseCommission { get; set; }
        public Nullable<decimal> CashCommission { get; set; }
        public Nullable<decimal> CarryingCommission { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> AdditionPrice { get; set; }
        public bool IsActive { get; set; }
        public long OrderDeliverDetailsId { get; set; }
    
        public virtual OrderDeliverDetail OrderDeliverDetail { get; set; }
        public virtual SaleReturn SaleReturn { get; set; }
    }
}
