//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSScheduleLog
    {
        public long SMSLogID { get; set; }
        public System.DateTime LogTime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
