//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransferDetail
    {
        public int StockTransferDetailId { get; set; }
        public Nullable<int> StockTransferId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> TransferQty { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public int IsReceived { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> BagQty { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual StockTransfer StockTransfer { get; set; }
    }
}
