//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreDetail()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public long StoreDetailId { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public double Qty { get; set; }
        public double RemainingQty { get; set; }
        public string BatchId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal ProductionRate { get; set; }
        public int BagQty { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal InvoiceValue { get; set; }
        public decimal LandedCost { get; set; }
        public decimal TotalCOGS { get; set; }
        public decimal CogsPerUnit { get; set; }
        public string ReceivedCode { get; set; }
        public Nullable<decimal> USDPrice { get; set; }
        public Nullable<decimal> BDTPrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual Store Store { get; set; }
    }
}
