//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticketing
    {
        public long Id { get; set; }
        public string TaskNo { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public int TaskType { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public long EmployeeId { get; set; }
    }
}
