//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long UserLogId { get; set; }
        public int ActionType { get; set; }
        public long EmployeeId { get; set; }
        public string EmpUserId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime ActionTimeStamp { get; set; }
        public string Details { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
