//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorOpening
    {
        public int VendorOpeningId { get; set; }
        public int VendorId { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public int VendorTypeId { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public decimal OpeningAmount { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsSubmit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual VendorType VendorType { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
