//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorOffer
    {
        public long VendorOfferId { get; set; }
        public int VendorId { get; set; }
        public int ProductId { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> BaseCommission { get; set; }
        public Nullable<decimal> CashCommission { get; set; }
        public Nullable<decimal> CarryingCommission { get; set; }
        public Nullable<decimal> SpecialCommission { get; set; }
        public Nullable<decimal> AdditionPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> FactoryCarryingCommission { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
