//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherBRMapDetail
    {
        public long VoucherBRMapDetailId { get; set; }
        public long VoucherBRMapMasterId { get; set; }
        public long VoucherDetailId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<long> BillRequisitionDetailId { get; set; }
        public Nullable<decimal> ApprovedQty { get; set; }
        public Nullable<decimal> ApprovedUnitRate { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public bool IsActive { get; set; }
    }
}
