//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public long VoucherDetailId { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public string Particular { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public bool IsActive { get; set; }
        public bool IsVirtual { get; set; }
    
        public virtual Voucher Voucher { get; set; }
    }
}
