//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.VoucherDetails = new HashSet<VoucherDetail>();
            this.VendorOpenings = new HashSet<VendorOpening>();
            this.VendorDeposits = new HashSet<VendorDeposit>();
        }
    
        public long VoucherId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string ChqNo { get; set; }
        public string ChqName { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<int> Accounting_CostCenterFk { get; set; }
        public string Narration { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string VoucherStatus { get; set; }
        public Nullable<int> VirtualHeadId { get; set; }
        public bool IsStock { get; set; }
        public bool IsSubmit { get; set; }
        public bool IsIntegrated { get; set; }
    
        public virtual VoucherType VoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDetail> VoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorOpening> VendorOpenings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorDeposit> VendorDeposits { get; set; }
    }
}
