//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Attendence
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> AttendenceDate { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<System.TimeSpan> TotalHour { get; set; }
        public string ShiftName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string EmpStatus { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public Nullable<long> HrAdminId { get; set; }
        public string ManagerName { get; set; }
        public string HRAdminName { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Department { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Company { get; set; }
        public Nullable<int> OfficeTypeId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> SalaryTag { get; set; }
    }
}
