//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDemandForSaleInvoice
    {
        public long DemandId { get; set; }
        public long DemandItemId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal DiscountUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public long Qty { get; set; }
        public decimal DiscountRate { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
    }
}
