//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductPrice
    {
        public Nullable<int> CompanyId { get; set; }
        public string PriceType { get; set; }
        public long Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string ProductName { get; set; }
    }
}
