//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSMSList
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public string PhoneNo { get; set; }
        public string Message { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> Status { get; set; }
        public int TryCount { get; set; }
        public System.DateTime RowTime { get; set; }
        public string Remarks { get; set; }
        public int SmsType { get; set; }
        public string SMSTypeName { get; set; }
        public string CompanyName { get; set; }
    }
}
