//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTeamLeaderList
    {
        public int Id { get; set; }
        public long EmployeeId { get; set; }
        public string TeamTitle { get; set; }
        public bool IsLeader { get; set; }
        public int CompanyId { get; set; }
        public string EmployeeName { get; set; }
        public string StrEmpId { get; set; }
        public string Designation { get; set; }
        public string CompanyName { get; set; }
    }
}
